.TH bluetooth 1 2020-01-31 "TLP 1.3.0" "Power Management"
.
.SH NAME
bluetooth \- enable/disable internal bluetooth device
.
.SH SYNOPSIS
.B bluetooth \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B on
Switch device on.
.
.TP
.B off
Switch device off.
.
.TP
.B toggle
Toggle device state.
.
.TP
<none>
Show device state.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH AUTHOR
(c) 2020 Thomas Koch <linrunner at gmx.net>
