.TH BLUETOOTH 1 "2014-10-03"

.SH NAME
bluetooth \- enable/disable internal bluetooth device
.SH SYNOPSIS
.B bluetooth \fR[\fIcommand\fR]

.SH COMMANDS

.TP
.B on
Switch device on.

.TP
.B off
Switch device off.

.TP
.B toggle
Toggle device state.

.TP
<none>
Show device state.

.SH SEE ALSO
.BR tlp (8).

.SH AUTHOR
Thomas Koch <linrunner at gmx.net>
