.TH bluetooth 1 2021-12-18 "TLP 1.6.0" "Power Management"
.
.SH NAME
bluetooth \- enable/disable internal bluetooth device
.
.SH SYNOPSIS
.B bluetooth \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B on
Switch device on.
.
.TP
.B off
Switch device off.
.
.TP
.B toggle
Toggle device state.
.
.TP
<none>
Show device state.
.
.SH SEE ALSO
.BR nfc (1),
.BR wifi (1),
.BR wwan (1),
.BR tlp (8).
.
.SH AUTHOR
(c) 2023 Thomas Koch <linrunner at gmx.net>
