.TH nfc 1 2021-10-15 "TLP 1.0" "Power Management"
.
.SH NAME
nfc \- enable/disable internal NFC device
.
.SH SYNOPSIS
.B nfc \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B on
Switch device on.
.
.TP
.B off
Switch device off.
.
.TP
.B toggle
Toggle device state.
.
.TP
<none>
Show device state.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH AUTHOR
(c) 2017 Thomas Koch <linrunner at gmx.net>
