.TH run-on-ac 1 2026-04-20 "TLP 1.10.0" "Power Management"
.
.SH NAME
run-on-ac - run command when on ac power
.
.SH SYNOPSIS
.B run-on-ac \fR\fIcommand\fR \fR[\fIarg(s)]\fR
.
.SH SEE ALSO
.BR run-on-bat (1),
.BR tlp (8).
.
.SH BUGS
Report bugs to: <https://github.com/linrunner/TLP/issues>.
.
.SH AUTHOR
(c) 2026 Thomas Koch <linrunner at gmx.net>
