.TH tlp\-usblist 1 2017-01-29 "TLP 1.0" "Power Management"
.
.SH NAME
tlp\-usblist \- show USB device data.
.
.SH SYNOPSIS
.B tlp\-usblist
.
.SH DESCRIPTION
List busnum, devnum, id, autosuspend controls, description and driver for all
devices.
.
.SH SEE ALSO
.BR tlp\-stat (8).
.
.SH NOTES
This command is called as a subroutine from tlp\-stat, do \fInot\fR invoke it
directly.

.SH AUTHOR
(c) 2017 Thomas Koch <linrunner at gmx.net>
