.TH tlp\-usblist 1 2017-01-24 "TLP 1.0" "Power Management"
.
.SH NAME
tlp\-usblist \- show USB device data.
.
.SH SYNOPSIS
.B tlp\-usblist
.
.SH DESCRIPTION
This command is called as a subroutine from tlp\-stat, do not invoke it directly.
.
.SH SEE ALSO
.BR tlp\-stat (8).
.
.SH AUTHOR
(c) 2017 Thomas Koch <linrunner at gmx.net>
