.TH TLP-STAT 8 "2012-03-21" "Power Management" ""
.SH NAME
tlp-stat \- show power management settings
.SH SYNOPSIS
.B tlp-stat \fI[option]\fR
.SH DESCRIPTION
This command shows the configuration, affected power management settings
and additional system info.

.SH OPTIONS
.TP
.B -b, --battery
Show battery data only.
.TP
.B -c, --config
Show configuration only.
.SH FILES
.I /etc/default/tlp
.RS
System configuration file containing all power management settings.
.SH SEE ALSO
.BR tlp (8).
.SH AUTHOR
Thomas Koch <linrunner@gmx.net>
