.TH TLP-STAT 8 "2015-01-24" "Power Management" ""

.SH NAME
tlp-stat \- show power management settings

.SH SYNOPSIS
.B tlp-stat \fI[option]\fR

.SH DESCRIPTION
This command shows the configuration, affected power management settings
and additional system info.

.SH OPTIONS

.TP
.B -b, --battery
Show battery data.

.TP
.B -c, --config
Show configuration.

.TP
.B -d, --disk
Show disk data.

.TP
.B -e, --pcie
Show PCI(e) device data.

.TP
.B -p, --processor
Show processor data.

.TP
.B -r, --rfkill
Show radio device data.

.TP
.B -s, --system
Show system information.

.TP
.B -t, --temp
Show temperatures and fan speed.

.TP
.B -u, --usb
Show USB device data.

.TP
.B -w, --warn
Show warnings.

.TP
.B -P, --pev
Monitor power supply udev events.

.TP
.B -T, --trace
Show trace output.

.TP
.B -v, --verbose
Be more verbose.

.SH FILES
.I /etc/default/tlp
.RS
System configuration file containing all power management settings.

.SH SEE ALSO
.BR tlp (8).

.SH AUTHOR
Thomas Koch <linrunner at gmx.net>
