.TH tlp 8 2017-01-29 "TLP 1.0" "Power Management"
.
.SH NAME
tlp \- apply laptop power saving settings
.
.SH SYNOPSIS
.B tlp \fIcommand\fR \fR[\fIparameter\fR] "..."
.
.SH DESCRIPTION
Apply power saving settings manually and control ThinkPad battery features.
.
.SH COMMANDS
.
.TP
.B start
Initialize \fBtlp\fR and apply power saving settings according to the actual
power source.
.
.TP
.B bat
Apply power saving settings for battery power source.
.
.TP
.B true
Same as \fBbat\fR (this command is called when power source changes to battery).
.
.TP
.B ac
Apply power saving settings for AC power source.
.
.TP
.B false
Same as \fBac\fR (this command is called when power source changes
to ac).
.
.TP
.B usb
Enable autosuspend for all USB devices, except blacklisted ones.
.
.TP
.B bayoff
Turn off optical drive in UltraBay/MediaBay.
The drive may be re\-enabled by pulling the eject lever or pushing the media
eject button on newer models.
.
.TP
.B setcharge [START_CHARGE STOP_CHARGE] [BAT0|BAT1] \fR(ThinkPads only)
Set charge thresholds of main (BAT0) or auxiliary (BAT1) battery temporarily.
Values must be between 1 and 100, STOP_CHARGE > START_CHARGE + 3.
Configured thresholds are restored upon next system boot-up. When called without
arguments, configured thresholds are set.
.
.TP
.B fullcharge [BAT0|BAT1] \fR(ThinkPads only)
Set charge thresholds of main (BAT0) or auxiliary (BAT1) battery to factory
presets (96/100) temporarily (causing a full charge).
Configured thresholds are restored upon next system boot-up.
.
.TP
.B chargeonce [BAT0|BAT1] \fR(ThinkPads only)
Charge main (BAT0) or auxiliary (BAT1) battery to the stop charge threshold once
(bypassing start threshold).
Configured thresholds are restored upon next system boot-up.
.
.TP
.B discharge [BAT0|BAT1] \fR(ThinkPads only)
Force complete discharge of main (BAT0) or auxiliary (BAT1) battery.
.
.TP
.B recalibrate [BAT0|BAT1] \fR(ThinkPads only)
Battery recalibration: completely discharge main (BAT0) or auxiliary (BAT1)
battery and recharge to 100%.
.
.TP
.B stat
Same as tlp\-stat.
.
.TP
.B diskid
Show disk ids for configuration.
.
.SH NOTES
For ThinkPads with more than one battery the selection works as follows:
.IP
BAT0 \- Main or internal battery
.IP
BAT1 \- Ultrabay, Slice or replaceable battery
.
.SH EXAMPLES
Apply thresholds of 70 / 90% to the main battery:
.IP
tlp setcharge 70 90 BAT0
.PP
Charge the auxiliary battery to full capacity:
.IP
tlp fullcharge BAT1
.PP
Recalibrate the main battery:
.IP
tlp recalibrate BAT0
.
.SH FILES
.I /etc/default/tlp
.RS
System-wide configuration file containing all power saving settings.
.
.SH EXIT STATUS
On success, 0 is returned, a non-zero failure code otherwise.
.
.SH SEE ALSO
.BR tlp\-stat (8),
.BR bluetooth (1),
.BR wifi (1),
.BR wwan (1).
.
.PP
.mso www.tmac
.URL "http://linrunner.de" "Project homepage: "
.
.SH AUTHOR
(c) 2017 Thomas Koch <linrunner at gmx.net>
