.TH tlp.service 8 2017-01-29 "TLP 1.0" "Power Management"
.
.SH NAME
.
tlp.service \- Initialize power saving at boot and cleanup upon shutdown
.
.SH SYNOPSIS
.B tlp\&.service
.
.SH DESCRIPTION
tlp.service executes the following tasks:
.IP " 1." 4
System boot-up: switch or restore radio states, apply power saving settings
and charge thresholds.
.IP " 2." 4
System shutdown: switch or save radio states, apply AC settings and cleanup.
.
.SH SEE ALSO
.BR tlp (8),
.BR tlp-sleep.service (8).
.
.SH NOTES
Do \fInot\fR employ tlp.service to refresh power saving settings after a
configuration change.
Use \fBtlp start\fR instead.
.
.SH AUTHOR
(c) 2017 Thomas Koch <linrunner at gmx.net>
