.TH TLP 8 "2015-01-03" "Power Management" ""

.SH NAME
tlp \- apply laptop power management settings
.SH SYNOPSIS
.B tlp \fIcommand\fR \fR[\fIparam\fR]

.SH DESCRIPTION
This command allows one to invoke TLP's functions manually and provides extended
battery functions for ThinkPads.

.SH COMMANDS

.TP
.B start
Initialize \fBtlp\fR and apply settings according to the actual power source.

.TP
.B bat
Apply settings for battery power source.

.TP
.B true
Same as \fBbat\fR (this command is called when power source changes to battery).

.TP
.B ac
Apply settings for ac power source.

.TP
.B false
Same as \fBac\fR (this command is called when power source changes
to ac).

.TP
.B usb
Enable autosuspend for all usb devices, except blacklisted ones.

.TP
.B bayoff 
Turn off optical drive in UltraBay/MediaBay. 
The drive may be re-enabled by pulling the eject lever or pushing the media eject button on newer models.

.TP
.B setcharge [START_CHARGE STOP_CHARGE] [BAT0|BAT1] \fR(ThinkPads only)
Set charge thresholds of main (BAT0) or Ultrabay (BAT1) battery temporarily. Values must be between 1 and 100, Stop > Start + 3. Configured thresholds are restored upon next system start. When called without arguments, configured thresholds are set.

.TP
.B fullcharge [BAT0|BAT1] \fR(ThinkPads only)
Set charge thresholds of main (BAT0) or Ultrabay (BAT1) battery to factory preset (96/100) temporarily (causing a full charge). Configured thresholds are restored upon next system start.

.TP
.B chargeonce [BAT0|BAT1] \fR(ThinkPads only)
Charge main (BAT0) or Ultrabay (BAT1) battery to upper charge threshold once (bypassing lower threshold). Configured thresholds are restored upon next system start.

.TP
.B discharge [BAT0|BAT1] \fR(ThinkPads only)
Force complete discharge of main (BAT0) or Ultrabay (BAT1) battery.

.TP
.B recalibrate [BAT0|BAT1] \fR(ThinkPads only)
Battery recalibration: completely discharge main (BAT0) or Ultrabay (BAT1) battery and recharge to 100%.

.TP
.B stat
Same as tlp-stat.

.TP
.B diskid
Show disk ids for configuration.

.SH FILES
.I /etc/default/tlp
.RS
System configuration file containing all power management settings.

.SH SEE ALSO
.BR tlp-stat (8),
.BR bluetooth (1),
.BR wifi (1),
.BR wwan (1).

.PP
.mso www.tmac
.URL "http://linrunner.de" "Project homepage: "

.SH AUTHOR
Thomas Koch <linrunner at gmx.net>
