.TH tlp 8 2022-11-28 "TLP 1.6.0" "Power Management"
.
.SH NAME
tlp \- apply laptop power saving settings
.
.SH SYNOPSIS
.B tlp \fIcommand\fR \fR[\fIparameters\fR] [\fB--\fR \fICONFIG_PARAM\fR\fB=\fIvalue\fR "..."]
.
.SH DESCRIPTION
\fBtlp\fR applies power saving settings manually and controls battery care
features.
.
.SH COMMANDS
.
.TP
.B start
Start \fBtlp\fR and apply power saving profile for the actual power source.
Also use to apply a changed configuration or to leave manual mode.
.
.TP
.B bat
Apply battery profile and enter manual mode.
Manual mode means that changes to the power source will be ignored until the
next reboot or \fBtlp start\fR is issued to resume automatic mode.
.
.TP
.B true
Alias for \fBbat\fR.
.
.TP
.B ac
Apply AC profile and enter manual mode.
Manual mode means that changes to the power source will be ignored until the
next reboot or \fBtlp start\fR is issued to resume automatic mode.
.
.TP
.B false
Alias for \fBac\fR.
.
.TP
.B usb
Enable autosuspend for all USB devices except those excluded by default or
via configuration.
.
.TP
.B bayoff
Turn off optical drive in UltraBay/MediaBay.
The drive may be re\-enabled by pulling the eject lever or pushing the media
eject button on newer models.
.
.PP
Note: charge threshold and recalibration commands below work for
specific laptop vendors and models only. Check the actual support status and
the value ranges with \fBtlp-stat -b\fR. For details on charge thresholds
also refer to the link at the bottom.
.TP
.B setcharge \fR[\fISTART_CHARGE_THRESH STOP_CHARGE_THRESH\fR] [\fBBAT0\fR|\fBBAT1\fR|\fBBAT\fR\fIx\fR|\fBCMB0\fR]
Change battery charge thresholds temporarily.
If your hardware supports only a stop threshold, set the start value to 0.
Configured charge thresholds will be restored at the next boot or by using
\fBtlp setcharge\fR again but without the threshold arguments.
.
.TP
.B fullcharge \fR[\fBBAT0\fR|\fBBAT1\fR|\fBBAT\fR\fIx\fR|\fBCMB0\fR]
Charge battery to full capacity.
This is done by applying vendor presets to the charge thresholds temporarily.
Configured charge thresholds will be restored at the next boot or by using
\fBtlp setcharge\fR without the threshold arguments.
.
.TP
.B chargeonce \fR[\fBBAT0\fR|\fBBAT1\fR] \fR(ThinkPads only)
Charge battery to the stop charge threshold once.
This is done by temporarily lifting the start charge threshold.
The configured start charge threshold will be restored at the next boot or by
using \fBtlp setcharge\fR without the threshold arguments.
.
.TP
.B discharge \fR[\fBBAT0\fR|\fBBAT1\fR] \fR(ThinkPads only)
Force a complete discharge of the battery while on AC power.
.
.TP
.B recalibrate \fR[\fBBAT0\fR|\fBBAT1\fR] \fR(ThinkPads only)
Perform a battery recalibration while on AC power: completely discharge the
battery and recharge to 100%. The latter is done by temporarily applying vendor
presets to the thresholds. Configured thresholds will be restored at the next
boot or by using \fBtlp setcharge\fR.
.
.TP
.B diskid
Show disk ids for configured drives.
.
.TP
.B \-- \fR\fICONFIG_PARAM\fR\fB=\fIvalue\fR "..."
Append configuration parameters to a command. These temporarily override
the system configuration during execution of that command only and are not
kept afterwards.
Disclaimer: this feature exists for the sole purpose of test automation
during TLP's development. It is provided as is and there is no support
whatsoever.
.
.SH NOTES
For laptops with more than one battery the selection works as follows:
.IP
BAT0 \- Main or internal battery
.IP
BAT1 \- Secondary or replaceable battery
.
.SH EXAMPLES
Change thresholds of the main battery to 70 / 90% temporarily:
.IP
tlp setcharge 70 90 BAT0
.PP
Charge the auxiliary battery to full capacity:
.IP
tlp fullcharge BAT1
.PP
Recalibrate the main battery:
.IP
tlp recalibrate BAT0
.
.SH FILES
.I /etc/tlp.conf
.RS
System-wide user configuration file, uncomment parameters here to override
default settings and customization files below.
.PP
.RE
.I /etc/tlp.d/*.conf
.RS
System-wide drop-in customization files, overriding defaults below.
.PP
.RE
.I /usr/share/tlp/defaults.conf
.RS
Intrinsic default settings. DO NOT EDIT this file, instead use one of the above
alternatives.
.PP
.RE
.I /run/tlp/run.conf
.RS
Effective settings consolidated from all above files. DO NOT CHANGE this file,
it is for reference only and regenerated on every invocation of TLP.
.PP
.RE
.I /etc/default/tlp
.RS
Obsolete system-wide configuration file. DO NOT USE this file, it is
evaluated only when /etc/tlp.conf is non-existent.
.
.SH EXIT STATUS
On success, 0 is returned, a non-zero failure code otherwise.
.
.SH SEE ALSO
.BR tlp\-stat (8),
.BR bluetooth (1),
.BR nfc (1),
.BR wifi (1),
.BR wwan (1).
.
.PP
.mso www.tmac
.URL "https://linrunner.de/tlp" "Project homepage: "
.PP
.URL "https://linrunner.de/tlp/settings/battery.html" \
  "Charge thresholds: "
.
.SH AUTHOR
(c) 2023 Thomas Koch <linrunner at gmx.net>
