.TH tlp.service 8 2021-12-18 "TLP 1.7.0" "Power Management"
.
.SH NAME
.
tlp.service - Initialize power saving at boot and cleanup upon shutdown
.
.SH SYNOPSIS
.B tlp\&.service
.
.SH DESCRIPTION
tlp.service executes the following tasks:
.IP " 1." 4
System boot-up: switch or restore radio states, apply power saving settings
and charge thresholds.
.IP " 2." 4
System shutdown: save radio states and cleanup.
.
.SH FILES
.I /lib/systemd/system-sleep/tlp
.RS
Applies power saving settings upon system suspend and resume.
.SH SEE ALSO
.BR tlp (8).
.
.SH NOTES
Do \fInot\fR employ tlp.service to refresh power saving settings after a
configuration change.
Use \fBtlp start\fR instead.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH AUTHOR
(c) 2024 Thomas Koch <linrunner at gmx.net>
