.TH wwan 1 2024-04-01 "TLP 1.7.0" "Power Management"
.
.SH NAME
wwan - enable/disable internal WWAN (3G/4G/5G) device
.
.SH SYNOPSIS
.B wwan \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B on
Switch device on.
.
.TP
.B off
Switch device off.
.
.TP
.B toggle
Toggle device state.
.
.TP
<none>
Show device state.
.
.TP
.B --version
Print TLP version.
.
SH SEE ALSO
.BR bluetooth (1),
.BR nfc (1),
.BR wifi (1),
.BR tlp (8).
.
.SH AUTHOR
(c) 2024 Thomas Koch <linrunner at gmx.net>
