.TH WWAN 1 "2014-10-03"

.SH NAME
wwan \- enable/disable internal wireless wan (umts) device

.SH SYNOPSIS
.B wwan \fR[\fIcommand\fR]

.SH COMMANDS

.TP
.B on
Switch device on.

.TP
.B off
Switch device off.

.TP
.B toggle
Toggle device state.

.TP
<none>
Show device state.

.SH SEE ALSO
.BR tlp (8).

.SH AUTHOR
Thomas Koch <linrunner at gmx.net>
