#!/bin/sh
# 10-thinkpad-legacy - Battery Feature Driver for ThinkPads using tp_smapi
# for thresholds and forced discharge,
# i.e. X201/T410 and older.
#
# Copyright (c) 2020 Thomas Koch <linrunner at gmx.net> and others.
# This software is licensed under the GPL v2 or later.

# Needs: tlp-func-base, 34-tlp-func-platform, 35-tlp-func-batt

# shellcheck disable=

batdrv_init () { # detect hardware and initialize driver
    # rc: 0=matching hardware detected/1=not detected

    echo_debug "bat" "batdrv_init.thinkpad-legacy.no_match"

    return 1
}
