#!/bin/sh
# tlp - disable Ultrabay on resume if it was disabled on the preceding suspend

. "${PM_FUNCTIONS}"

CFG=/etc/default/tlp
STATE=tp_bay_off

get_bay () {
	dock=$(grep -l ata_bay /sys/devices/platform/dock.?/type)
	dock=${dock%%/type}
	if [ ! -d "$dock" ]; then
		dock=""
	fi
}

suspend_bay () {
	get_bay
	if [ -n "$dock" ]; then
		if [ -e $dock/docked ]; then
			if [ "$(cat $dock/docked)" = "0" ]; then
				savestate $STATE 1
			fi
		fi
	fi
}

resume_bay () {
	local cnt
	local rc
	
	state_exists $STATE || return
	[ "$(restorestate $STATE)" = "1" ] || return
		
	get_bay
	if [ -n "$dock" ]; then
		if [ -e $dock/undock ]; then
			cnt=5
			rc=1
			until [ $rc = 0 -o $cnt = 0 ]; do
				cnt=$((cnt - 1))
				echo 1 > $dock/undock
				rc=$?
				[ $rc = 0 ] || sleep 0.5
			done
			return 0
		fi
	fi
}

[ -f $CFG ] || exit 0
. $CFG

[ "$TLP_ENABLE" = "1" -a "$BAY_POWEROFF_ON_BAT" = "1" ] || exit 0

case $1 in
	hibernate|suspend)
		suspend_bay
		;;
		
	thaw|resume)
		resume_bay
		;;
		
	*) exit $NA
		;;
esac

