#!/bin/sh
# tlp - set sata link power to max_performance during suspend/resume
# Code from http://www.thinkwiki.org/wiki/Suspend/Resume_Support_For_SATA_Link_Power_Management

BASEDIR=/sys/class/scsi_host/
[ -d $BASEDIR ] || exit 0

. /usr/lib/pm-utils/functions

suspend_sata() {
	local host
	
	for host in ${BASEDIR}/* ; do
		if [ -e ${host}/link_power_management_policy ]; then
			local policy=$(cat ${host}/link_power_management_policy)
			savestate ${host##/*/}_link_power_management_policy "${policy}"
			echo max_performance > ${host}/link_power_management_policy
			echo $host $policy >> /tmp/sata.log ## DEBUG
		fi
	done
}

resume_sata() {
	local host
	
	for host in ${BASEDIR}/* ; do
		if [ -e ${host}/link_power_management_policy ]; then
			local policy=$(restorestate $(echo ${host##/*/}_link_power_management_policy))
			echo ${policy} > ${host}/link_power_management_policy
			echo $host $policy >> /tmp/sata.log ## DEBUG
		fi
	done
}

case "$1" in
	suspend|hibernate)
		suspend_sata
		;;
		
	resume|thaw)
		resume_sata
		;;
		
	*)
		;;
esac

exit 0 # $?
