TLP_PERSISTENT_DEFAULT # Parameter is deprecated. Use TLP_AUTO_SWITCH=0 together with TLP_PROFILE_DEFAULT!
DEVICES_TO_DISABLE_ON_SHUTDOWN # Parameter has been removed. It can be deleted from your config.
DEVICES_TO_ENABLE_ON_SHUTDOWN # Parameter has been removed. It can be deleted from your config.
RADEON_DPM_STATE_ON_AC # Parameter has been removed. It can be deleted from your config.
RADEON_DPM_STATE_ON_BAT # Parameter has been removed. It can be deleted from your config.
RADEON_DPM_STATE_ON_SAV # Parameter has been removed. It can be deleted from your config.
RADEON_POWER_PROFILE_ON_AC # Parameter has been removed. It can be deleted from your config.
RADEON_POWER_PROFILE_ON_BAT # Parameter has been removed. It can be deleted from your config.
RESTORE_DEVICE_STATE_ON_STARTUP # Parameter has been removed. It can be deleted from your config.
SCHED_POWERSAVE_ON_AC # Parameter has been removed. It can be deleted from your config.
SCHED_POWERSAVE_ON_BAT # Parameter has been removed. It can be deleted from your config,
USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN # Parameter has been removed. It can be deleted from your config,
