#!/bin/sh
# tlp - adjust power settings 

# Source library
LIB=/usr/lib/tlp/tlp-functions
if [ ! -f $LIB ]; then
	echo "Error: missing function library \'$LIB\'."
	exit 1
fi
. $LIB

RFLIB=/usr/lib/tlp/tlp-rf-func
if [ ! -f $LIB ]; then
	echo "Error: missing function library \'$RFLIB\'."
	exit 1
fi
. $RFLIB

# MAIN
read_defaults
check_tlp_enabled || exit 1
check_laptop_mode_tools || exit 2

# Get cmd line arg
mode=$(echo $1 | tr "[:upper:]" "[:lower:]")

case "$mode" in
	start) # Set start power mode depending on state
		check_root
		get_power_state
		pwr=$?
		load_tp_smapi
		
		set_laptopmode $pwr
		set_dirty_parms $pwr
		set_phc_controls $pwr
		set_disk_apm_level $pwr
		set_sata_link_power $pwr
		set_wifi_power_mode $pwr
		disable_wake_on_lan $pwr
		set_sound_power_mode $pwr
		enable_usb_suspend
		[ "$pwr" = "1" ] && poweroff_drivebay 0
		set_charge_thresholds
		;;

	true|bat*) # Set battery power mode
		check_root
		set_laptopmode 1
		set_dirty_parms 1
		set_phc_controls 1
		set_disk_apm_level 1
		set_sata_link_power 1
		set_wifi_power_mode 1
		disable_wake_on_lan 1
		set_sound_power_mode 1
		enable_usb_suspend
		poweroff_drivebay 0
		;;
		
	false|ac) # Set ac power mode
		check_root
		set_laptopmode 0
		set_dirty_parms 0
		set_phc_controls 0
		set_disk_apm_level 0
		set_sata_link_power 0
		set_wifi_power_mode 0
		disable_wake_on_lan 0
		set_sound_power_mode 0
		enable_usb_suspend
		;;
		
	wifi) # Set wifi power mode depending on state
		check_root
		get_power_state
		pwr=$?
		
		set_wifi_power_mode $pwr
		;;

	usb) # Enable usb autosuspend
		check_root
		enable_usb_suspend
		;;

	bayoff) # Power off drive bay
		check_root
		poweroff_drivebay 1
		;;
		
	xlogin) # Disable bluetooth on desktop login
		for dev in $DEVICES_TO_DISABLE_ON_STARTUP; do
			[ "$dev" = "bluetooth" ] && device_off $dev
		done
		;;
		
	discharge) # Discharge battery completely
		check_root
		load_tp_smapi
		discharge_battery $2
		;;
		
	*) 
		echo "Usage: tlp start|true|bat|false|ac|wifi|usb|bayoff|xlogin|discharge"
		;;
esac

exit 0


