#!/bin/sh
# tlp - systemd suspend/resume hook
#
# Copyright (c) 2026 Thomas Koch <linrunner at gmx.net> and others.
# SPDX-License-Identifier: GPL-2.0-or-later

[ -f ]

case $1 in
    pre)  tlp suspend ;;
    post) tlp resume  ;;
esac
