#!/bin/sh
# tlp - handle added usb devices

# --- Definitions
LOGGER=logger

USBD=/sys/bus/usb/devices
USB_TIMEOUT=2
USB_TIMEOUT_MS=2000
USB_DONE=/var/run/tlp.usb-done

CFG=/etc/default/tlp

# --- Subroutines
echo_debug () { # $1: tag; $2: msg; echo debug msg if tag matches 
   if [ -z "${TLP_DEBUG##*$1*}" ] ; then
        $LOGGER -p debug -t "tlp[$$,$PPID]" "$2"
   fi
}

# --- MAIN

# Discard subdevice events
usbdev=$1
[ -n "${usbdev##*:*}" ] || exit 0 

# Exit when usb startup flag is not set
[ -f $USB_DONE ] || exit 0

# Read config
[ -f $CFG ] || exit 0
. $CFG

# Check if enabled
[ "$TLP_ENABLE" = "1" ] && [ "$USB_AUTOSUSPEND" = "1" ] || exit 0

# Handle device
if [ -f $USBD/$usbdev/power/autosuspend ] || [ -f $USBD/$usbdev/power/autosuspend_delay_ms ]; then
    # device is autosuspendable
    ctrlf="control"
    autof="autosuspend_delay_ms"
    usbid="$(cat $USBD/$usbdev/idVendor):$(cat $USBD/$usbdev/idProduct)"
    busdev="Bus $(cat $USBD/$usbdev/busnum) Dev $(cat $USBD/$usbdev/devnum)"
            
    control="auto"
    hid=""
    if [ -z "${USB_BLACKLIST##*$usbid*}" ]; then
        # device is in blacklist
        control="on"
    else
        # check for hid subdevices
        for subdev in $USBD/$usbdev/*:*; do
            if [ -L $subdev/driver ]; then
                driver=$(readlink $subdev/driver)
                if [ "${driver##*/}" = "usbhid" ]; then
                    control="on"
                    hid="_hid"
                    break
                fi
            fi
        done    
    fi
        
    if [ -f $USBD/$usbdev/power/control ]; then
        echo "$control" > $USBD/$usbdev/power/control
    else
        # level is deprecated
        echo "$control" > $USBD/$usbdev/power/level
        ctrlf="level"
    fi
    
    if [ -f $USBD/$usbdev/power/autosuspend_delay_ms ]; then
        echo $USB_TIMEOUT_MS > $USBD/$usbdev/power/autosuspend_delay_ms 2> /dev/null
        if [ $? != 0 ]; then
            # openSUSE 11.4/2.6.37: writing to autosuspend_delay_ms fails -> fallback to autosuspend
            echo_debug "usb" "udev_usb.autosuspend_delay_ms_not_writable: $busdev ID $usbid $USBD/$usbdev"
            echo $USB_TIMEOUT > $USBD/$usbdev/power/autosuspend
            autof="autosuspend"
        fi
    else
        # autosuspend is deprecated
        echo $USB_TIMEOUT > $USBD/$usbdev/power/autosuspend
        autof="autosuspend"
    fi
    
    echo_debug "usb" "udev_usb.$control$hid: $busdev ID $usbid $USBD/$usbdev [$ctrlf $autof]"
fi

exit 0


