#!/bin/sh
# tlp - run commands depending on power source
#
# Copyright (c) 2014 Thomas Koch <linrunner at gmx.net>
# This software is licensed under the GPL v2 or later.

# --- Constants
readonly LIBDIRS="/usr/lib/tlp-pm /usr/lib64/tlp-pm"
readonly LIBS="tlp-functions"

# --- Locate and source libraries
for libdir in $LIBDIRS; do [ -d $libdir ] && break; done
if [ ! -d $libdir ]; then
    echo "Error: missing library directory ($LIBDIRS)."
    exit 1
fi

for lib in $LIBS; do
    if [ ! -f $libdir/$lib ]; then
        echo "Error: missing function library \'$libdir/$lib\'."
        exit 1
    fi
    . $libdir/$lib
done

# --- MAIN
self=${0##*/}

cmd=$1
if [ -z "$1" ]; then
    echo "Usage: $self command [arg(s)]"
    exit 1
fi

shift

case $self in
    run-on-ac)
        if get_power_state; then
            $cmd $@
        fi
        ;;

    run-on-bat)
        if ! get_power_state; then
            $cmd $@
        fi
        ;;

    *)
        echo "Error: unknown mode $self."
        exit 1
        ;;
esac
