#!/bin/sh
# tlp - switch bluetooth/wifi/wwan on/off

RFLIB=/usr/lib/tlp/tlp-rf-func
[ -f $RFLIB ] || exit 0
. $RFLIB

self=${0##*/}

case $self in
    bluetooth|wifi|wwan)
		case $1 in
			on)
				device_on $self
				echo_device_state $self
				;;

			off)
				device_off $self
				echo_device_state $self
				;;
				
			toggle)
				device_toggle $self
				echo_device_state $self
				;;
				
			*)
				echo_device_state $self
				;;
		esac
        ;;

    *)
		echo "Error: unknown device type \"$self\"."
		exit 1
		;;
esac

exit 0
