#!/bin/sh
# tlp - rf switch functions
#
# Copyright (c) 2015 Thomas Koch <linrunner at gmx.net>
# This software is licensed under the GPL v2 or later.

# ----------------------------------------------------------------------------
# Constants

readonly RFKILL="rfkill"
readonly RFKD="/dev/rfkill"

readonly ALLDEV="bluetooth wifi wwan"


# ----------------------------------------------------------------------------
# Functions

get_devc () { # get control device for radio type -- $1: rftype; retval $devc
    local i

    check_sysfs "get_devc" "/sys/class/rfkill"

    devc=""
    devs=254
    rfkdev="1"
    devon="1"
    devoff="0"

    case $1 in
        wwan|bluetooth)
            for i in /sys/class/rfkill/rfkill* ; do
                if [ -f $i/type ] && [ "$(cat $i/type)" = "$1" ]; then
                    devc="$i/state"
                    echo_debug "rf" "get_devc($1) = $devc"
                    return 0
                fi
            done
            ;;

        wifi)
            for i in /sys/bus/pci/drivers/ipw2?00/*/rf_kill; do
                if [ -f $i ]; then
                    devc="$i"
                    rfkdev="0"
                    devon="0"
                    devoff="1"
                    echo_debug "rf" "get_devc($1) = $devc"
                    return 0
                fi
            done

            for i in /sys/class/rfkill/rfkill* ; do
                if [ -f $i/type ] && [ "$(cat $i/type)" = "wlan" ]; then
                    devc="$i/state"
                    echo_debug "rf" "get_devc($1) = $devc"
                    return 0
                fi
            done
            ;;

        *)
            echo "Error: unknown device type \"$1\"" 1>&2
            echo_debug "rf" "get_devc($1).unknown_type"
            return 0
            ;;
    esac

    echo_debug "rf" "get_devc($1).not_present"

    return 0
}

get_devs () { # get radio device state -- $1: rftype; retval $devs: 0=off/1=on
    if [ -n "$devc" ]; then
        devs=$(cat $devc)
        [ "$rfkdev" = "0" ] && devs=$(($devs ^ $devoff))
    fi

    echo_debug "rf" "get_devs($1) = $devs"

    return 0
}

err_no_root_priv () { # check root privilege
    echo "Error: missing root privilege." 1>&2
    echo_debug "rf" "$1.missing_root_privilege"

    return 0
}

test_rfkill_perms () { # test if either root priv or rfkill device writable
    test_root || [ -w $RFKD ]
}

check_nm () { # test if NetworkManager is running and nmcli is installed

    cmd_exists $NMCLI
}

invoke_nmcli () { # call nmcli with radio option according to the program version
                  # $1: rftype, $2: on/off, $3: caller; rc: last nmcli rc
    local rc

    [ "$X_NO_NMCLI" = "1" ] && return 0 # return if nmcli disabled

    check_nm || return 0 # return if NetworkManager not running

    $NMCLI nm $1 $2 > /dev/null 2>&1; rc=$?
    echo_debug "rf" "invoke_nmcli($1, $2).nm: rc=$rc"
    if [ $rc -eq 2 ]; then
        # option "nm" is invalid for this NM version, try "radio" instead
        $NMCLI radio $1 $2 > /dev/null 2>&1; rc=$?
        echo_debug "rf" "invoke_nmcli($1, $2).radio: rc=$rc"
    fi

    return $rc
}

device_state () { # get radio type state -- $1: rftype; retval $devc, $devs: 0=off/1=on
    echo_debug "rf" "device_state($1)"

    get_devc $1
    get_devs $1
}

device_on () { # enable radio type -- $1: rftype
    echo_debug "rf" "device_on($1)"

    get_devc $1

    # quit if no device
    [ -z "$devc" ] && return 0

    # get device state
    get_devs $1

    if [ "$devs" = "0" ]; then
        # device is currently off --> turn rfkill device state on
        if [ "$rfkdev" = "1" ] && cmd_exists $RFKILL ; then
            if test_rfkill_perms ; then
                echo_debug "rf" "device_on($1).rfkill"
                $RFKILL unblock $1 > /dev/null 2>&1
                get_devs $1
            else
                err_no_root_priv "device_on($1).rfkill"
            fi
        else
            if test_root ; then
                echo_debug "rf" "device_on($1).devc"
                echo -n $devon > $devc
                get_devs $1
            else
                err_no_root_priv "device_on($1).devc"
            fi
        fi
    fi

    # use nmcli to notify NM that device is now on
    case "$1" in
        wifi|wwan)
            invoke_nmcli $1 on
            ;;
    esac

    # get/record final device state
    get_devs $1

    return 0
}

device_off () { # disable radio type -- $1: rftype
    echo_debug "rf" "device_off($1)"

    get_devc $1

    # quit if no device
    [ -z "$devc" ] && return 0

    # get device state
    get_devs $1

    if [ "$devs" = "1" ]; then
        # device is currently on --> turn rfkill device state off
        if [ "$rfkdev" = "1" ] && cmd_exists $RFKILL ; then
            if test_rfkill_perms ; then
                echo_debug "rf" "device_off($1).rfkill"
                $RFKILL block $1 > /dev/null 2>&1
                get_devs $1
            else
                err_no_root_priv "device_off($1).rfkill"
            fi
        else
            if test_root ; then
                echo_debug "rf" "device_off($1).devc"
                echo -n $devoff > $devc
                get_devs $1
            else
                err_no_root_priv "device_off($1).devc"
            fi
        fi
    fi

    # use nmcli to notify NM that device is now off
    case "$1" in
        wifi|wwan)
            invoke_nmcli $1 off
            ;;
    esac

    # get/record final device state
    get_devs $1

    return 0
}

device_toggle () { # toggle radio type state -- $1: rftype
    echo_debug "rf" "device_toggle($1)"

    get_devc $1

    # quit if no device
    [ -z "$devc" ] && return 0

    # get device state
    get_devs $1

    # toggle rfkill device state
    if [ "$rfkdev" = "1" ] && cmd_exists $RFKILL ; then
        if test_rfkill_perms ; then
            echo_debug "rf" "device_toggle($1).rfkill"
            case $devs in
                0) $RFKILL unblock $1 > /dev/null 2>&1 ;;
                1) $RFKILL block $1   > /dev/null 2>&1 ;;
                *) ;;
            esac
            get_devs $1
        else
            err_no_root_priv "device_toogle($1).rfkill"
        fi
    else
        if test_root ; then
            echo_debug "rf" "device_toggle($1).devc"
            case $devs in
                0) echo -n $devon > $devc ;;
                1) echo -n $devoff > $devc ;;
                *) ;;
            esac
            get_devs $1
        else
            err_no_root_priv "device_toogle($1).devc"
        fi
    fi

    # use nmcli to notify NM of new device state
    case "$1" in
        wifi|wwan)
            case $devs in
                1) invoke_nmcli $1 on  ;;
                0) invoke_nmcli $1 off ;;
                *) ;;
            esac
            ;;
    esac

    # get/record final device state
    get_devs $1

    return 0
}

device_set_state () { # set radio type state -- $1: rftype, $2: state 0=off/1=on
    echo_debug "rf" "device_set_state($1, $2)"

    get_devc $1

    # quit if no device
    [ -z "$devc" ] && return 0

    # quit if state not 0 nor 1
    [ "$2" = "0" ] || [ "$2" = "1" ] || return 0

    # get device state
    get_devs $1

    # set rfkill device state
    if [ "$rfkdev" = "1" ] && cmd_exists $RFKILL ; then
        if test_rfkill_perms ; then
            echo_debug "rf" "device_set_state($1, $2).rfkill"
            case $2 in
                0) $RFKILL block $1   > /dev/null 2>&1 ;;
                1) $RFKILL unblock $1 > /dev/null 2>&1 ;;
            esac
            get_devs $1
        else
            err_no_root_priv "device_set_state($1).rfkill"
        fi
    else
        if test_root ; then
            echo_debug "rf" "device_set_state($1, $2).devc"
            case $2 in
                0) echo -n $devoff > $devc ;;
                1) echo -n $devon > $devc ;;
            esac
            get_devs $1
        else
            err_no_root_priv "device_set_state($1, $2).devc"
        fi
    fi

    # use nmcli to notify NM of new device state
    case "$1" in
        wifi|wwan)
            case $devs in
                1) invoke_nmcli $1 on  ;;
                0) invoke_nmcli $1 off ;;
                *) ;;
            esac
            ;;
    esac

    # get/record final device state
    get_devs $1

    return 0
}

echo_device_state () { # print radio type state -- $1: rftype, $2: state
    case $1 in
        bluetooth)
            devstr="bluetooth"
            ;;

        wifi)
            devstr="wifi     "
            ;;

        wwan)
            devstr="wwan     "
            ;;

        *)
            devstr=$1
            ;;
    esac

    case $2 in
        0)
            echo "$devstr = off (software)"
            ;;

        1)
            echo "$devstr = on"
            ;;

        2)
            echo "$devstr = off (hardware)"
            ;;

        254)
            echo "$devstr = none (no device)"
            ;;

        *)
            echo "$devstr = unknown state \"$2\""
    esac

    return 0
}

save_device_states () { # save radio states  -- $1: list of rftypes
    local dev
    local devlist="${1:-$ALLDEV}" # when arg empty -> use all

    echo_debug "rf" "save_device_states($devlist)"

    # create empty state file
    mkdir -p $STATEDIR 2> /dev/null 1>&2
    : > $RFSTATEFILE

    # iterate over all possible devices -> save state in file
    for dev in $devlist; do
        device_state $dev
        echo "$dev $devs" >> $RFSTATEFILE
    done

    return 0
}

restore_device_states () { # restore radio type states
    local sline

    echo_debug "rf" "restore_device_states"

    if [ -f $RFSTATEFILE ]; then
        # read state file
        while read sline; do
            set -- $sline # read dev, state into $1, $2
            device_set_state $1 $2
        done < $RFSTATEFILE

        return 0
    else
        return 1
    fi
}

set_radio_device_states () { # set/initialize all radio states
    # $1: start/stop/1/0/radiosw
    # called from init scripts or upon change of power source
    local dev devs2disable devs2enable restore
    local quiet=0

    # save/restore mode is disabled by default
    if [ "$1" != "radiosw" ]; then
        restore=${RESTORE_DEVICE_STATE_ON_STARTUP:-0}
    else
        restore=0
    fi

    if [ "$restore" = "1" ]; then
        # "save/restore" mode
        echo_debug "rf" "set_radio_device_states($1).restore"
        case $1 in
            start)
                restore_device_states
                if [ $? = 0 ]; then
                    echo "Radio device states restored."
                else
                    echo "No saved radio device states found."
                fi
                ;;

            stop)
                save_device_states
                echo "Radio device states saved."
                ;;
        esac
    else
        # "disable/enable on startup/shutdown or bat/ac" or "radiosw" mode
        case $1 in
            start) # system startup
                devs2disable="$DEVICES_TO_DISABLE_ON_STARTUP"
                devs2enable="$DEVICES_TO_ENABLE_ON_STARTUP"
                ;;

            stop) # system shutdown
                devs2disable="$DEVICES_TO_DISABLE_ON_SHUTDOWN"
                devs2enable="$DEVICES_TO_ENABLE_ON_SHUTDOWN"

                # NM workaround: when not explicitly configured,
                # re-enable wifi on shutdown to prepare for startup
                if ! wordinlist "wifi" "$devs2disable $devs2enable"; then
                    devs2enable="wifi $devs2enable"
                fi
                ;;

            1) # battery power --> build disable list
                quiet=1 # do not display progress
                devs2enable=""
                devs2disable="${DEVICES_TO_DISABLE_ON_BAT:-}"

                # check configured list for connected devices
                for dev in ${DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE:-}; do
                    case $dev in
                        bluetooth) any_bluetooth_in_use ;;
                        wifi) any_wifi_in_use ;;
                        wwan) any_wwan_in_use ;;
                    esac
                    # if device is not connected and not in list yet --> add to disable list
                    [ $? = 0 ] || wordinlist $dev "$devs2disable" || devs2disable="$dev $devs2disable"
                done
                devs2disable="${devs2disable# }"
                ;;

            0) # AC power --> build enable list
                quiet=1 # do not display progress
                devs2enable="${DEVICES_TO_ENABLE_ON_AC:-}"
                devs2disable=""
                ;;

            radiosw)
                devs2disable=""
                devs2enable="$DEVICES_TO_ENABLE_ON_RADIOSW"
                ;;
        esac

        echo_debug "rf" "set_radio_device_states($1): enable=$devs2enable disable=$devs2disable"

        # Disable configured radios
        if [ -n "$devs2disable" ]; then
            [ "$quiet" = "1" ] || echo -n "Disabling radios:"
            for dev in $devs2disable; do
                [ "$quiet" = "1" ] || echo -n " $dev"
                device_off $dev
            done
            [ "$quiet" = "1" ] || echo "."
        fi

        # Enable configured radios
        if [ -n "$devs2enable" ]; then
            if [ "$1" = "radiosw" ]; then
                # radiosw mode: disable radios not listed
                for dev in bluetooth wifi wwan; do
                    if ! wordinlist "$dev" "$devs2enable"; then
                        device_off $dev
                    fi
                done
            else
                # start mode: enable listed radios
                [ "$quiet" = "1" ] || echo -n "Enabling radios:"
                for dev in $devs2enable; do
                    [ "$quiet" = "1" ] || echo -n " $dev"
                    device_on $dev
                done
                [ "$quiet" = "1" ] || echo "."
            fi
        fi

        # clean up: discard state file
        rm -f $RFSTATEFILE 2> /dev/null
    fi

    return 0
}
