#!/bin/sh
# tlp - ifup hook
IWC=/sbin/iwconfig
TLP=/usr/sbin/tlp

[ -x $IWC ] || exit 0
[ -x $TLP ] || exit 0

if [ -z $($IWC $IFACE 2>&1 | grep "no wireless extensions") ]; then
    # interface is wifi
    $TLP wifi $IFACE
fi

exit 0
