#!/bin/sh
# tlp-rdw-nm - network manager dispatcher hook: disable radios on ifup
#
# Copyright (c) 2012 Thomas Koch <linrunner at gmx.net>
# This software is licensed under the GPL v2.

# --- Definitions
LIB=/usr/lib/tlp-pm/tlp-functions
RFLIB=/usr/lib/tlp-pm/tlp-rf-func

# --- Source libraries
[ -f $LIB ] || exit 0
. $LIB

[ -f $RFLIB ] || exit 0
. $RFLIB

# --- MAIN
read_defaults
check_tlp_enabled || exit 1

echo_debug "nm" "rdw_nm($*)"

# Check params
IFACE="$1"
ACTION="$2"

[ "$ACTION" = "up" ] && [ -n "$IFACE" ] && [ "$IFACE" != "none" ] || exit 0

# Determine interface type
case $IFACE in
    ppp*) # usb wwan: iface != dev
        if [ -n "$($NMCLI dev | egrep 'gsm.*connected')" ]; then 
            ITYPE="gsm"
        fi
        ;;

    *) # general case: iface = dev
        ITYPE="$($NMCLI dev | awk '$1 ~ /'$IFACE'/ { print $2; }')"
        ;;
esac

echo_debug "nm" "rdw_nm.rfkill_other: iface=$IFACE type=$ITYPE"

# rfkill other interfaces
case $ITYPE in
    802-3-ethernet)
	    if [ "$($IP -4 addr show $IFACE)" != "${X_IP_IGNORE:-x.y.z.t}" ]; then
	        for dev in $DEVICES_TO_DISABLE_ON_LAN_CONNECT; do 
                [ -n "$dev" ] && device_off $dev
            done
        fi
        ;;
            
    802-11-wireless)
        for dev in $DEVICES_TO_DISABLE_ON_WIFI_CONNECT; do 
            [ -n "$dev" ] && device_off $dev
        done
        ;;
            
    gsm)
        for dev in $DEVICES_TO_DISABLE_ON_WWAN_CONNECT; do 
            [ -n "$dev" ] && device_off $dev
        done
        ;;
            
    *) # do nothing
        ;;
esac

exit 0
