#!/bin/sh

### BEGIN INIT INFO
# Provides:          tlp
# Required-Start:    $remote_fs $all
# Required-Stop:     $remote_fs $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tlp start/stop script
# Description:       Initialize tlp
### END INIT INFO

case "$1" in
    start|\
    stop|\
    restart|\
    force-reload|\
    *)
        TLP=/usr/sbin/tlp
        [ -x $TLP ] && $TLP init $1 upwr
        ;;
esac

exit 0
