.TH tlp-pd.service 8 2025-10-27 "TLP 1.9.0" "Power Management"
.
.SH NAME
.
tlp-pd.service - starts the TLP Profiles Daemon (tlp-pd)
.
.SH SYNOPSIS
.B tlp-pd\&.service
.
.SH DESCRIPTION
tlp-pd implements the D-Bus interface org.freedesktop.UPower.PowerProfile
which lets desktop environments show a power profile switch.
TLP is used as the backend to apply these profiles.
.
.SH SEE ALSO
.BR tlp (8), tlp-pd (8)
.
.SH AUTHOR
(c) 2025 Thomas Koch <linrunner at gmx.net>
