.TH tlp-pd.service 8 2025-10-11 "TLP-PD 1.9.0" "Power Management"
.
.SH NAME
.
tlp-pd.service - starts the TLP Profiles Daemon (TLP-PD)
.
.SH SYNOPSIS
.B tlp-pd\&.service
.
.SH DESCRIPTION
TLP-PD implements the D-Bus interface org.freedesktop.UPower.PowerProfile
which is displayed in desktop environments as a power profile switch.
TLP is used as the backend to apply these profiles.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH AUTHOR
(c) 2025 Thomas Koch <linrunner at gmx.net>
