.TH tlp-pd 8 2025-10-16 "TLP-PD 1.9.0" "Power Management"
.
.SH NAME
.
tlp-pd - TLP Profiles Daemon
.
.SH SYNOPSIS
.B tlp-pd \fB[\fIoptions\fR]
.
.SH DESCRIPTION
tlp-pd implements the D-Bus interface org.freedesktop.UPower.PowerProfile
which lets desktop environments show a power profile switch.
TLP is used as the backend to apply these profiles.

.SH OPTIONS
.
.TP
.B -D, --debug
Write debug information to the system log. You can view it using
\fBtlp-stat --trace\fR.

.
.SH SEE ALSO
.BR tlp (8), tlp-pd.service (8).
.
.SH AUTHOR
(c) 2025 Thomas Koch <linrunner at gmx.net>
