.TH tlp-pd.service 8 2026-04-07 "TLP 1.10.0-beta.2" "Power Management"
.
.SH NAME
.
tlp-pd.service - starts the TLP Profiles Daemon (tlp-pd)
.
.SH SYNOPSIS
.B tlp-pd\&.service
.
.SH DESCRIPTION
tlp-pd implements the D-Bus interface org.freedesktop.UPower.PowerProfile
which lets desktop environments show a profile switch.
TLP is used as the backend to apply these profiles.
.
.SH SEE ALSO
.BR tlp (8), tlp-pd (8)
.
.SH BUGS
Report bugs to: <https://github.com/linrunner/TLP/issues>.
.
.SH AUTHOR
(c) 2026 Thomas Koch <linrunner at gmx.net>
