#!/bin/sh
### BEGIN INIT INFO
# Provides:          tlp
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tlp start/stop script
# Description:       Initialize tlp settings
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

TLP=/usr/sbin/tlp
LIB=/usr/lib/tlp/tlp-functions
RFLIB=/usr/lib/tlp/tlp-rf-func
CFG=/etc/default/tlp

[ -x $TLP ] || exit 0
[ -f $LIB ] || exit 0
[ -f $RFLIB ] || exit 0
[ -f $CFG ] || exit 0

. $LIB
. $RFLIB
read_defaults

echo_debug "run" "+++ init.d $1"
check_tlp_enabled || exit 0

case $1 in
	start|restart|force-reload)
			
		for dev in $DEVICES_TO_DISABLE_ON_STARTUP; do
			if [ "$dev" != "bluetooth" -o "$X_BT_DISABLE_ON_INIT" = "1" ]; then
				device_off $dev
			fi
		done
	
		load_tp_smapi
		set_charge_thresholds
		;;
		
	stop)
		for dev in $DEVICES_TO_DISABLE_ON_SHUTDOWN; do
			device_off $dev
		done
	
		load_tp_smapi
		set_charge_thresholds
		;;

	*)
		# do nothing
		;;
esac

exit 0
