#! /bin/sh
### BEGIN INIT INFO
# Provides:          tlp
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tlp start/stop script
# Description: 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

TLP=/usr/sbin/tlp
LIB=/usr/lib/tlp/tlp-functions
RFLIB=/usr/lib/tlp/tlp-rf-func
CFG=/etc/default/tlp

[ -x $TLP ] || exit 0
[ -f $LIB ] || exit 0
[ -f $RFLIB ] || exit 0
[ -f $CFG ] || exit 0

. $LIB
. $RFLIB
. $CFG

check_tlp_enabled || exit 0

case $1 in
	start)
		$TLP start
		
		for dev in $DEVICES_TO_DISABLE_ON_STARTUP; do
			device_off $dev
		done
		;;
		
	stop)
		$TLP false
		
		for dev in $DEVICES_TO_DISABLE_ON_SHUTDOWN; do
			device_off $dev
		done
		;;

	*)
		# do nothing
		;;
esac

exit 0
