.TH TLP-STAT 8 "2010-01-23" "Power Management" ""
.SH NAME
tlp-stat \- show system's power management settings
.SH SYNOPSIS
.B tlp-stat
.SH DESCRIPTION
This command shows all power management settings that are
affected by \fBtlp\fR and some additional system info.
.SH FILES
.I /etc/default/tlp
.RS
System configuration file containing all power management settings.
.SH SEE ALSO
.BR tlp (8).
.SH AUTHOR
Thomas Koch <linrunner@gmx.net>
