#!/bin/sh -e
#DEBHELPER#

# Disable conflicting pm-utils hooks
for i in 95hdparm-apm disable_wol hal-cd-polling intel-audio-powersave harddrive \
         laptop-mode journal-commit pci_devices pcie_aspm readahead sata_alpm \
         sched-powersave usb_bluetooth wireless xfs_buffer; do
    if [ -x /usr/lib/pm-utils/power.d/$i ]; then
        ln -sf /usr/lib/tlp-pm/tlp-nop /etc/pm/power.d/$i
    fi
done
