.TH WWAN 1 "2010-09-11"
.SH NAME
wwan \- enable/disable internal wireless wan (umts) device
.SH SYNOPSIS
.B wwan \fR[\fIcommand\fR]
.SH COMMANDS
.TP
.B on
Switch device on.
.TP
.B off
Switch device off.
.TP
.B toggle
Toggle device state.
.TP
<none>
Show device state.
.SH AUTHOR
Thomas Koch <linrunner@gmx.net>
