.TH tlp-rdw 8 2020-01-31 "TLP 1.4.0" "Power Management"
.
.SH NAME
tlp-rdw \- disable Radio Device Wizard temporarily (until reboot).
.
.SH SYNOPSIS
.B tlp-rdw \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B disable
Disable RDW actions.
.
.TP
.B enable
Enable RDW actions.
.
.TP
<none>
Show RDW state.
.
.SH AUTHOR
(c) 2021 Thomas Koch <linrunner at gmx.net>
