.TH tlp-rdw 8 2026-04-07 "TLP 1.10.0-beta.2" "Power Management"
.
.SH NAME
tlp-rdw - disable Radio Device Wizard temporarily (until reboot).
.
.SH SYNOPSIS
.B tlp-rdw \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B disable
Disable RDW actions.
.
.TP
.B enable
Enable RDW actions.
.
.TP
<none>
Show RDW state.
.
.TP
.B --version
Print TLP version.
.
.SH AUTHORIZATION
.PP
The \fBtlp-rdw\fR command requires root privileges for enabling/disabling actions.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH BUGS
Report bugs to: <https://github.com/linrunner/TLP/issues>.
.
.SH AUTHOR
(c) 2026 Thomas Koch <linrunner at gmx.net>
