.TH tlp-rdw 8 2025-10-27 "TLP 1.9.0" "Power Management"
.
.SH NAME
tlp-rdw - disable Radio Device Wizard temporarily (until reboot).
.
.SH SYNOPSIS
.B tlp-rdw \fR[\fIcommand\fR]
.
.SH COMMANDS
.
.TP
.B disable
Disable RDW actions.
.
.TP
.B enable
Enable RDW actions.
.
.TP
<none>
Show RDW state.
.
.TP
.B --version
Print TLP version.
.
.SH AUTHORIZATION
.PP
The \fBtlp-rdw\fR command requires root privileges for enabling/disabling actions.
.
.SH SEE ALSO
.BR tlp (8).
.
.SH AUTHOR
(c) 2025 Thomas Koch <linrunner at gmx.net>
